### ISSUE TITLE
App crashes attempting to download BuildGDX and doesn't download any mod

### ISSUE THREAD

**Issue by Mancubuss** [fgsfds/BuildLauncher#13]
Using build 0.25, first time for the app.

It found all the games installed, I downloaded all the ports successfully just pressing 'Install' and expected the same experience for other downloads. However, when I press 'Install' for BuildGDX, the app waits couple seconds, then mouse pointer changes to hour glass and almost immediately app closes. The port remains not installed when I relaunch the app.

As for mods and other downloads, the app doesn't seem to do anything when I choose the file I intend to download and press now enabled 'Download' at the bottom, no matter what the source is. The links where they are available, are opened in a browser successfully.

**Comment by fgsfds** [comment]
BuildGDX downloading is fixed in https://github.com/fgsfds/BuildLauncher/releases/tag/0.25.1

As for mods downloading, it works fine for me. Can you upload `buildgdx.log` after trying to download something?

**Comment by Mancubuss** [comment]
I have deleted the log and attempted to download two files with different URLs:

`[Information] BuildLauncher version: 0.25.2.0
[Information] Operating system: Microsoft Windows NT 10.0.26100.0
[Information] Working folder is f:\Other\Build Launcher
[Information] Looking for new app release
[Information] Looking for new ports releases
[Information] Latest release for EDuke32: r10593
[Information] Found Windows release for BuildLauncher: 0.25.2
[Information] Latest Windows release for Raze: 1.10.2
[Information] Latest Linux release for Raze: 1.9.1
[Information] Latest Windows release for NBlood: r14124
[Information] Latest Windows release for RedNukem: r14124
[Information] Latest Windows release for PCExhumed: r14124
[Information] Latest Windows release for NotBlood: 11/14/2024 01:55:53
[Information] Latest Linux release for NotBlood: 11/14/2024 01:55:49
[Critical] === Critical error ===
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Common.Client.Tools.ArchiveTools.DownloadFileAsync(Uri url, String filePath)
   at Addons.Providers.DownloadableAddonsProvider.DownloadAddonAsync(IDownloadableAddon addon)
   at Avalonia.Desktop.ViewModels.DownloadsViewModel.DownloadAddon()
[Critical] === Critical error ===
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Common.Client.Tools.ArchiveTools.DownloadFileAsync(Uri url, String filePath)
   at Addons.Providers.DownloadableAddonsProvider.DownloadAddonAsync(IDownloadableAddon addon)
   at Avalonia.Desktop.ViewModels.DownloadsViewModel.DownloadAddon()
`

But - I have connected to VPN outside of my country (which is Ukraine) and downloaded couple successfully. Have no idea what's going on, as same files were successfully downloaded with browser without VPN.

**Comment by Mancubuss** [comment]
BTW, I didn't check downloading BuildGDX at first, but - 0.25.2 crashes the same way as 0.25.0 did. But, again, I thought I should try VPN here as well - and it did download successfully. Have no idea mate, what is so different between other ports and BuildGDX and mods that first were downloaded successfully without any issues and latter cause issues for me.

**Comment by fgsfds** [comment]
Other ports are downloaded from their official github repos while BGDX and addons are downloaded from my own storage.
And it looks like the storage I use is blocked in Ukraine. Or vice versa. My options for the storage with reasonable pricing are limited but I'll see what I can do about this.

**Comment by Mancubuss** [comment]
Oh, makes sense man. Don't worry about it then, it's not your problem :) Thanks for clearing this up for me

**Comment by fgsfds** [comment]
@Mancubuss can you check if you can download this file without vpn?

https://s3.fgsfds.link/buildlauncher/Duke3D/Campaigns/duke3d-blast-radius_v5_0_6.zip

**Comment by Mancubuss** [comment]
Hey man. I still can't and now I know the reason, it's on some of the .ru domains that were blocked. I didn't bother looking into where it downloads from before but now it makes sense.

Don't worry about it.

**Comment by Mancubuss** [comment]
I mean, it still doesn't download from the app, but from the link provided above, with the browser, it downloads, as it's on AWS I assume.

**Comment by fgsfds** [comment]
>but from the link provided above, with the browser, it downloads, as it's on AWS I assume.

That's good to hear. I will update the app once I move files to that server.

**Comment by fgsfds** [comment]
Done, downloads should work now
